// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCivcacxMkIVXRi5gSdL1aAOVr5T-huOpQ',
    appId: '1:440920170749:web:85f3d96c6fbd17d2dd1e94',
    messagingSenderId: '440920170749',
    projectId: 'mavis-crm-80885',
    authDomain: 'mavis-crm-80885.firebaseapp.com',
    storageBucket: 'mavis-crm-80885.firebasestorage.app',
    measurementId: 'G-26P1YPNN2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlFzu2D-t2m0CPGVCxpU2TbvRU0EN4fqA',
    appId: '1:440920170749:android:eaedc262c8876e21dd1e94',
    messagingSenderId: '440920170749',
    projectId: 'mavis-crm-80885',
    storageBucket: 'mavis-crm-80885.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADA3Z_axA0yTJaSJxduWMLhfGAk8vMeNk',
    appId: '1:440920170749:ios:3a74f3bb32f3a69bdd1e94',
    messagingSenderId: '440920170749',
    projectId: 'mavis-crm-80885',
    storageBucket: 'mavis-crm-80885.firebasestorage.app',
    iosBundleId: 'com.mavis.mavis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADA3Z_axA0yTJaSJxduWMLhfGAk8vMeNk',
    appId: '1:440920170749:ios:3a74f3bb32f3a69bdd1e94',
    messagingSenderId: '440920170749',
    projectId: 'mavis-crm-80885',
    storageBucket: 'mavis-crm-80885.firebasestorage.app',
    iosBundleId: 'com.mavis.mavis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCivcacxMkIVXRi5gSdL1aAOVr5T-huOpQ',
    appId: '1:440920170749:web:66cd1f3278dd3a26dd1e94',
    messagingSenderId: '440920170749',
    projectId: 'mavis-crm-80885',
    authDomain: 'mavis-crm-80885.firebaseapp.com',
    storageBucket: 'mavis-crm-80885.firebasestorage.app',
    measurementId: 'G-GPKHYYQQ1E',
  );
}
